services:
  - type: web
    name: tennis-club-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production

